name: python-lint-test

on:
  push:
    branches:
      - main
    paths:
      - app.py

jobs:
  auto-format-and-lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do repositório
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    # Passo 2: Configuração do ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Passo 3: Instalação das dependências (flake8 e autopep8)
    - name: Install Dependencies
      run: |
        pip install flake8
        pip install autopep8

    # Passo 4: Formatação automática do código
    - name: Fix Code Formatting
      run: autopep8 -v --in-place --recursive app.py

    # Passo 5: Verificação do lint nos arquivos Python
    - name: Lint Python Files
      run: flake8 app.py
      
    # Passo 6: Commit e push das alterações
    - name: Commit & Push Changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        repository: juam-sv/chatgpt-labs
        branch: main
